packages:
  - 'Advent of Code'
  - 'Choosing the correct frontendframework in 2024'
  - 'Frontend testing workshop'
  - 'Intro to Kotlin'
  - 'Intro to Vite'
  - 'Mapping of Web Rendering/slides'
  - 'Mapping of Web Rendering/slides/theme'
  - 'Reactivity in frontend frameworks and whats the deal with signals'
  - 'Whats new in JavaScript - ES2021'
  - 'Whats new in JavaScript - ES2022'
  - 'Whats new in JavaScript - ES2023'
  - 'Which Framework Do You Like'