name: CI/CD slides

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: pnpm install
        run: |
          cd slides
          pnpm install
      - name: build Intro to Vite
        run: |
          cd "slides/Intro to Vite"
          pnpm build
          mv dist ../web/intro-to-vite
      - name: build Whats new in JavaScript - ES2021
        run: |
          cd "slides/Whats new in JavaScript - ES2021"
          pnpm build
          mv dist ../web/whats-new-in-javascript-es2021
      - name: build Which Framework Do You Like
        run: |
          cd "slides/Which Framework Do You Like"
          pnpm build:slides
          mv dist ../web/which-framework-do-you-like
      - name: build Which Framework Do You Like - Voting app
        run: |
          cd "slides/Which Framework Do You Like"
          pnpm build:voting
          mv voting-app/dist ../web/which-framework-do-you-like-voting      
      - name: build Intro to Kotlin
        run: |
          cd "slides/Intro to Kotlin"
          pnpm build
          mv dist ../web/intro-to-kotlin
      - name: build Frontend testing workshop
        run: |
          cd "slides/Frontend testing workshop"
          pnpm build
          mv dist ../web/frontend-testing-workshop
      - name: build Whats new in JavaScript - ES2022
        run: |
          cd "slides/Whats new in JavaScript - ES2022"
          pnpm build
          mv dist ../web/whats-new-in-javascript-es2022
      - name: build Mapping of Web Rendering
        run: |
          cd "slides/Mapping of Web Rendering/slides"
          pnpm build
          mv dist ../../web/mapping-of-web-rendering
      - name: build Whats new in JavaScript - ES2023
        run: |
          cd "slides/Whats new in JavaScript - ES2023"
          pnpm build
          mv dist ../web/whats-new-in-javascript-es2023
      - name: build Whats new in JavaScript - ES2023
        run: |
          cd "slides/Reactivity in frontend frameworks and whats the deal with signals"
          pnpm build
          mv dist ../web/reactivity-in-frontend-frameworks-and-whats-the-deal-with-signals
      - name: build Choosing the correct frontendframework in 2024
        run: |
          cd "slides/Choosing the correct frontendframework in 2024"
          pnpm build
          mv dist ../web/choosing-the-correct-frontendframework-in-2024
      - name: How I built Kuizzi
        run: |
          cd "slides/How I built Kuizzi"
          pnpm build
          mv dist ../web/how-i-built-kuizzi
      - name: Help we have to create the new frontend framework
        run: |
          cd "slides/Help we have to create the new frontend framework"
          pnpm build
          mv dist ../web/help-we-have-to-create-the-new-frontend-framework
      - name: deploy
        run: |
          netlify deploy --dir slides/web --prod --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}  --site ${{ secrets.NETLIFY_SITE_ID }}
