name: CI/CD slides

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build Intro to Vite
        run: |
          cd "slides/Intro to Vite"
          npm build
          mv dist intro-to-vite ../web
      - name: deploy
          cd slides
          netlify deploy --prod --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}  --site ${{ secrets.NETLIFY_SITE_ID }}
