name: CI/CD slides

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build Intro to Vite
        run: |
          cd "slides/Intro to Vite"
          npm i
          npm run build
          mv dist ../web/intro-to-vite
      - name: deploy
        run: |
          cd slides
          netlify deploy --dir web --prod --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}  --site ${{ secrets.NETLIFY_SITE_ID }}
